# SPDX-FileCopyrightText: 2025 Ethersecurity Inc.
#
# SPDX-License-Identifier: MPL-2.0
# Author: Shohei KAMON <cameong@stir.network>

name: Publish to Homebrew

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag push
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
          - os: ubuntu-latest
            arch: amd64  # WSL Linux build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pyinstaller
        run: |
          python -m pip install pyinstaller

      - name: Build Intel binary (x86_64) with PyInstaller
        if: matrix.arch == 'x86_64'
        run: |
          pyinstaller --onefile --name fireblocks-cli fireblocks_cli/main.py
          mkdir -p release/fireblocks-cli-${{ github.ref_name }}-x86_64
          mv dist/fireblocks-cli release/fireblocks-cli-${{ github.ref_name }}-x86_64/fireblocks-cli
          tar -czvf fireblocks_cli-${{ github.ref_name }}-macos-x86_64.tar.gz -C release fireblocks-cli-${{ github.ref_name }}-x86_64
          sha256sum fireblocks_cli-${{ github.ref_name }}-macos-x86_64.tar.gz > fireblocks_cli-${{ github.ref_name }}-macos-x86_64.tar.gz.sha256

      - name: Build ARM binary (arm64) with PyInstaller
        if: matrix.arch == 'arm64'
        run: |
          pyinstaller --onefile --name fireblocks-cli fireblocks_cli/main.py
          mkdir -p release/fireblocks-cli-${{ github.ref_name }}-arm64
          mv dist/fireblocks-cli release/fireblocks-cli-${{ github.ref_name }}-arm64/fireblocks-cli
          tar -czvf fireblocks_cli-${{ github.ref_name }}-macos-arm64.tar.gz -C release fireblocks-cli-${{ github.ref_name }}-arm64
          sha256sum fireblocks_cli-${{ github.ref_name }}-macos-arm64.tar.gz > fireblocks_cli-${{ github.ref_name }}-macos-arm64.tar.gz.sha256

      - name: Build Linux binary (amd64) with PyInstaller (for WSL)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxrandr-dev libpng-dev
          pyinstaller --onefile --name fireblocks-cli fireblocks_cli/main.py
          mkdir -p release/fireblocks-cli-${{ github.ref_name }}-amd64
          mv dist/fireblocks-cli release/fireblocks-cli-${{ github.ref_name }}-amd64/fireblocks-cli
          tar -czvf fireblocks_cli-${{ github.ref_name }}-linux-amd64.tar.gz -C release fireblocks-cli-${{ github.ref_name }}-amd64
          sha256sum fireblocks_cli-${{ github.ref_name }}-linux-amd64.tar.gz > fireblocks_cli-${{ github.ref_name }}-linux-amd64.tar.gz.sha256

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fireblocks_cli-${{ github.ref_name }}-macos-x86_64.tar.gz
            fireblocks_cli-${{ github.ref_name }}-macos-arm64.tar.gz
            fireblocks_cli-${{ github.ref_name }}-linux-amd64.tar.gz
            fireblocks_cli-${{ github.ref_name }}-macos-x86_64.tar.gz.sha256
            fireblocks_cli-${{ github.ref_name }}-macos-arm64.tar.gz.sha256
            fireblocks_cli-${{ github.ref_name }}-linux-amd64.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
